{{<<"text">>, <<"@vavroom check my video of us rescuing a hedgehog from our soccer net: http://bit.ly/bKQnvg">>},
{<<"in_reply_to_screen_name">>,<<"vavroom">>},
{<<"truncated">>,false},
{<<"place">>,null},
{<<"in_reply_to_status_id">>,11343183236},
{<<"source">>,
                  <<"<a href=\"http://www.tweetdeck.com\" rel=\"nofollow\">TweetDeck</a>">>},
{<<"coordinates">>,null},
{<<"geo">>,null},
{<<"favorited">>,false},
{<<"in_reply_to_user_id">>,17242190},
{<<"contributors">>,null},
{<<"user">>,
                  {{<<"lang">>,<<"en">>},
                   {<<"statuses_count">>,9484},
                   {<<"profile_link_color">>,<<"0000ff">>},
                   {<<"location">>,<<"Auckland, New Zealand">>},
                   {<<"following">>,null},
                   {<<"profile_background_image_url">>,
                    <<"http://a3.twimg.com/profile_background_images/21877053/sand.jpg">>},
                   {<<"profile_image_url">>,
                    <<"http://a3.twimg.com/profile_images/700633123/BenGPSReviewSquare_normal.png">>},
                   {<<"contributors_enabled">>,false},
                   {<<"profile_sidebar_fill_color">>,<<"90856f">>},
                   {<<"profile_background_tile">>,true},
                   {<<"description">>,
                    <<"Software architect with Datacom, TVNZ gadget reviewer. I am a sponge. I absorb technical information voraciously.">>},
                   {<<"screen_name">>,<<"nzben">>},
                   {<<"profile_sidebar_border_color">>,<<"866a23">>},
                   {<<"url">>,<<"http://www.ben.geek.nz">>},
                   {<<"verified">>,false},
                   {<<"geo_enabled">>,false},
                   {<<"followers_count">>,2103},
                   {<<"friends_count">>,316},
                   {<<"profile_background_color">>,<<"90856f">>},
                   {<<"protected">>,false},
                   {<<"notifications">>,null},
                   {<<"favourites_count">>,45},
                   {<<"name">>,<<"Ben Gracewood">>},
                   {<<"created_at">>,<<"Fri Sep 15 07:01:18 +0000 2006">>},
                   {<<"profile_text_color">>,<<"2e2b23">>},
                   {<<"id">>,6136},
                   {<<"time_zone">>,<<"Auckland">>},
                   {<<"utc_offset">>,43200}}},
{<<"id">>,11343312591},
{<<"created_at">>,<<"Wed Mar 31 02:35:01 +0000 2010">>}}